### ISSUE TITLE
Content Inventory - Welcome

### ISSUE THREAD

**Issue by wesruv** [wesruv/jungcentralohio.org#11]
Parent Issue: https://github.com/wesruv/jungcentralohio.org/issues/3

http://www.jungcentralohio.org/Welcome.html

Information we're trying to collect for the page above and it's sub-pages:
- [ ] How the pages/section fit into the site-tree/navigation
- [ ] Identify chunks of content that make up the page (e.g. the page is an 'event', but also has listings of upcoming events OR the page is the "about us page" but also has a listing of seminars, a summary of the lending library, and it lists the board members)
- [ ] Identify any 'special' functionality or behaviors. This includes search, listings of content, animating/interactive elements, etc.
- [ ] *Extra credit*, if you have any recommendations (e.g. this page might be better with a picture of X, or this piece of content could use a map, this page could be combined with another, etc)

**Comment by starbuck28** [comment]
# Welcome

A page linked to from the main menu as an introduction to the site

- Page Header (text)
- JACO Logo
- Content Main Header
- Subheader
- Welcome message

**Comment by wesruv** [comment]
Looks great!
