### ISSUE TITLE
Content Inventory - Other Regional Events

### ISSUE THREAD

**Issue by wesruv** [wesruv/jungcentralohio.org#12]
Parent Issue: https://github.com/wesruv/jungcentralohio.org/issues/3

http://www.jungcentralohio.org/regionalEvents.html

Information we're trying to collect for the page above and it's sub-pages:
- [ ] How the pages/section fit into the site-tree/navigation
- [ ] Identify chunks of content that make up the page (e.g. the page is an 'event', but also has listings of upcoming events OR the page is the "about us page" but also has a listing of seminars, a summary of the lending library, and it lists the board members)
- [ ] Identify any 'special' functionality or behaviors. This includes search, listings of content, animating/interactive elements, etc.
- [ ] *Extra credit*, if you have any recommendations (e.g. this page might be better with a picture of X, or this piece of content could use a map, this page could be combined with another, etc)

**Comment by pascalmp** [comment]
#  Other Regional Events

The page looks like it has a website(cleveland chapiter) within a website, this would probably just be a link that redirects to that external website.

As for the actual Page , it would still contain : 

Page header

- image logo
- org. name
- Phone number
- registration/login
- Navbar (collapsible, links to other major pages)

Body area

- Text title
- text body
- Related links
- Can use a clickable image of the regional associations

Sidebar

- Registration links to other regional associations
- Links to partner sites

Footer
- Links to major pages
- name of org.

**Comment by wesruv** [comment]
Yea, this was a weird one, looks good!
