### ISSUE TITLE
Content Inventory - Second Saturday Discussions

### ISSUE THREAD

**Issue by wesruv** [wesruv/jungcentralohio.org#13]
Parent Issue: https://github.com/wesruv/jungcentralohio.org/issues/3

http://www.jungcentralohio.org/saturday.html

Information we're trying to collect for the page above and it's sub-pages:
- [ ] How the pages/section fit into the site-tree/navigation
- [ ] Identify chunks of content that make up the page (e.g. the page is an 'event', but also has listings of upcoming events OR the page is the "about us page" but also has a listing of seminars, a summary of the lending library, and it lists the board members)
- [ ] Identify any 'special' functionality or behaviors. This includes search, listings of content, animating/interactive elements, etc.
- [ ] *Extra credit*, if you have any recommendations (e.g. this page might be better with a picture of X, or this piece of content could use a map, this page could be combined with another, etc)

**Comment by pascalmp** [comment]
# Second Saturday Discussions
 heading area:
- image logo
- org. name
- Phone number
- registration/login
- Navbar (collapsible, links to other major pages)

Body area:

- image for 25th celebration(or future anniversaries)
- Welcome text to Event
- Time and Directions(Maps)
- List of upcoming and past events(Maybe thumbnails with links to expand text)
- Donations link(would direct to their paypal page that will also have(or not) a button in the footer

Sidebar
- link to Gallery
- links to pdf files
- a search bar

Footer

- Links to major pages
- name of org. 
- Paypal donations or other forms of donations links/buttons with their respective logos

**Comment by wesruv** [comment]
Looks good!
