### ISSUE TITLE
Content Inventory - 4th Saturday Member's Gathering

### ISSUE THREAD

**Issue by wesruv** [wesruv/jungcentralohio.org#14]
Parent Issue: https://github.com/wesruv/jungcentralohio.org/issues/3

http://www.jungcentralohio.org/4th_saturday.html

Information we're trying to collect for the page above and it's sub-pages:
- [ ] How the pages/section fit into the site-tree/navigation
- [ ] Identify chunks of content that make up the page (e.g. the page is an 'event', but also has listings of upcoming events OR the page is the "about us page" but also has a listing of seminars, a summary of the lending library, and it lists the board members)
- [ ] Identify any 'special' functionality or behaviors. This includes search, listings of content, animating/interactive elements, etc.
- [ ] *Extra credit*, if you have any recommendations (e.g. this page might be better with a picture of X, or this piece of content could use a map, this page could be combined with another, etc)

**Comment by pascalmp** [comment]
# 4th Saturday Members' Gathering
Page has the following content areas:

1.Header containing:

- Small logo image

- Name

- Phone number button

- register/login links

2.Navbar containing:

- links to other pages of the site
- I'm thinking a transparent one giving the effect of links floating, 
- we can put a circular background under each link, if that's not too much)
- collapsible

3.Body area containing

- Title of the event
- Time of the event
- info about the event

- Maps(directions)

- Maybe a picture (of choice) or video of past event

- It says "Free for members", would probably need a link for event registration payment

. Side bar containing

- Links to upcoming and past event
-Photo Gallery for past events

4.Footer area

- Links(like in the navbar)

- Copyrights and other text

**Comment by wesruv** [comment]
Looks good!
