### ISSUE TITLE
Content Inventory - Recent Programs

### ISSUE THREAD

**Issue by wesruv** [wesruv/jungcentralohio.org#16]
Parent Issue: https://github.com/wesruv/jungcentralohio.org/issues/3

http://www.jungcentralohio.org/recentPRO.html

Information we're trying to collect for the page above and it's sub-pages:
- [ ] How the pages/section fit into the site-tree/navigation
- [ ] Identify chunks of content that make up the page (e.g. the page is an 'event', but also has listings of upcoming events OR the page is the "about us page" but also has a listing of seminars, a summary of the lending library, and it lists the board members)
- [ ] Identify any 'special' functionality or behaviors. This includes search, listings of content, animating/interactive elements, etc.
- [ ] *Extra credit*, if you have any recommendations (e.g. this page might be better with a picture of X, or this piece of content could use a map, this page could be combined with another, etc)

**Comment by CraigKaminski** [comment]
# Recent JACO Programs

A list of past programs

* Reached via the "Recent Programs" link on the homepage and "recent" link at the bottom of all pages
* Each program entry consists of:
  * Date(s)
  * Title
  * Presenter(s)
* The entire program entry is a link to a flyer
* The flyers are typically PDFs, but some are HTML documents
* The programs for 2016 and 2015 are visible
* The 2016 programs are separated from the 2015 programs by a horizontal rule
* There are headings for the years previous to 2015 in the form of "YYYY Programs"
* Clicking a year heading triggers an animation which reveals a list of programs for that year
* Clicking a year heading a second time triggers an animation which hides the list of programs
* Clicking a year heading does not cause listings for other years to be hidden if visible
* Bottom of page has links to most pages listed on homepage, but not all

**Comment by wesruv** [comment]
Looks good!
