### ISSUE TITLE
Content Inventory - Bollinger Lectures

### ISSUE THREAD

**Issue by wesruv** [wesruv/jungcentralohio.org#17]
Parent Issue: https://github.com/wesruv/jungcentralohio.org/issues/3

http://www.jungcentralohio.org/bollingen.html

Information we're trying to collect for the page above and it's sub-pages:
- [ ] How the pages/section fit into the site-tree/navigation
- [ ] Identify chunks of content that make up the page (e.g. the page is an 'event', but also has listings of upcoming events OR the page is the "about us page" but also has a listing of seminars, a summary of the lending library, and it lists the board members)
- [ ] Identify any 'special' functionality or behaviors. This includes search, listings of content, animating/interactive elements, etc.
- [ ] *Extra credit*, if you have any recommendations (e.g. this page might be better with a picture of X, or this piece of content could use a map, this page could be combined with another, etc)

**Comment by CraigKaminski** [comment]
# The Bollingen Lectures
* Details of current year's lecture and list of past years lectures
* Reached via the "The Bollingen Lectures" link on the homepage and "bollingen" link at the bottom of all pages
* "THE BOLLINGEN LECTURES" heading at top of page
* JACO 25 years image
* The current year's lecture details include the following:
  * Year of lecture in the form of "YYYY BOLLINGEN LECTURE"
  * Presenter
  * Title
  * Subtitle
  * Dates
  * Location
    * Location is a link to JACO page which consists of:
      * Heading with name of location
      * Embedded Google Map of location
      * Usual set of links at bottom of page
  * Jung quote
  * Details of Friday lecture consisting of:
    * Heading of the form "Friday Lecture: TITLE"
    * Description
    * Number of continuing education units for psychologists, counselors, and social worker
    * "See Flyer for details." Link to lecture flyer, which is a PDF
    * "Register for event." Link to Eventzilla to register for Lecture and/or Workshop
  * Details of Saturday workshop consisting of:
    * Heading of the form "Saturday Workshop: TITLE"
    * Description
    * Number of continuing education units for psychologists, counselors, and social worker
    * "See Flyer for details." Link to lecture flyer, which is a PDF
    * "Register for event." Link to Eventzilla to register for Lecture and/or Workshop
  * Name of presenter in bold followed by their background
  * Link to lecture flyer, which is a PDF
  * Link to Eventzilla to register for Lecture and/or Workshop
  * "Register for" list of upcoming events each of the form:
    *  Image with month and day of event
    * Title of event which is a link to Eventzilla
    * Date and time of event
    * Location of event
    * The "Register for" list appears to be generated by an Eventzilla plugin
* “Previous Bollinger Lectures” Heading
* Reverse chronological order list of yearly Bollingen lectures consisting of:
  * Year
  * Lecturer
  * Title
  * Year and title are link to flyer
* Description of Bollinger Lecuter
* Request for donations with mailing address

**Comment by wesruv** [comment]
Looks great!

I'd list "Details of Friday lecture" and "Details of Saturday workshop" one type of content used twice since they seem to be uniform.
