### ISSUE TITLE
Data Structure  - Event

### ISSUE THREAD

**Issue by wesruv** [wesruv/jungcentralohio.org#22]
Events are a content type for any gathering they plan, gallery exhibit, regular workshops, one off special events, etc.

* Name
* Description
* Date, Start & End
* Price
* Image
* Number of seats

We may want to try and create repeating events, but I think that will take some research to figure out how do-able that is.

Leaving off Location, speaker, and registration link for now.

Related content from the old site:
* https://github.com/wesruv/jungcentralohio.org/issues/17
* https://github.com/wesruv/jungcentralohio.org/issues/10
* https://github.com/wesruv/jungcentralohio.org/issues/16
* https://github.com/wesruv/jungcentralohio.org/issues/13

**Comment by starbuck28** [comment]
Wes, I went ahead and created multidev Starbuck12 for this content type. A couple of questions and this may be thinking too far ahead.... but if we need to add a location to the event but we already have a content type for location, how do we combine the two? Are we still going to link to Eventzilla for the event registration (I can't remember if we talked about this)? Thanks!

**Comment by wesruv** [comment]
@starbuck28 
Oh, I forgot to leave a note about these, I left them off intentionally!

For location, there's a new(ish) feature coming up in Backdrop 1.6 that we'll use to make this easier.

Yes we are using Eventzilla, I'm not sure how exactly we'll tie it together, the easiest route would be a link to the Eventzilla site, but there's a chance we could do something cooler. Want to leave it off for now.

Great job catching that stuff, sorry I forgot to write a note for those two items!

**Comment by wesruv** [comment]
@starbuck28 hah, just figured out that I didn't look at the back of the card where I took my notes, we'll also need a field for # of seats. Updated issue description.

**Comment by wesruv** [comment]
Took a look at what you have so far and it looks great!

**Comment by wesruv** [comment]
@starbuck28 any more progress to look at?

**Comment by starbuck28** [comment]
Not yet. I'll add it tonight. Sorry! :(

**Comment by wesruv** [comment]
No worries!

**Comment by starbuck28** [comment]
Ok- I added a field for the number of seats.

**Comment by wesruv** [comment]
Looks great!
