### ISSUE TITLE
Data Structure - Library Item

### ISSUE THREAD

**Issue by wesruv** [wesruv/jungcentralohio.org#32]
This content type will be an item from their library or store, we'll likely need to add more fields to this later, but for now we're going to stick with what we know.

* Name
* Description
* Price
* Image
* Published/Created Year
* Amazon Link

Intentionally leaving out Medium (Book/CD/etc) and Credits/Author/Artist for now.

Related content from old site:
* https://github.com/wesruv/jungcentralohio.org/issues/8

**Comment by maryeb** [comment]
Spun up a multi-dev on Pantheon for this issue. Feedback is welcome.

**Comment by wesruv** [comment]
That environment is at: http://maryeb-32-jaco.pantheonsite.io/

**Comment by wesruv** [comment]
@maryeb a little bit of feedback:
On Amazon Link we won't need a "Link Title", just the URL, the link text (title) will always be the same and we can set that when we make the templates.

Everything else looks great!

Let me know when that's updated and I'll get it moved to the other environments!

**Comment by maryeb** [comment]
@wesruv Do you mean under "Link Title" I should mark "no title" in the options? (If so, this is done)
 Or is there some way I'm supposed to get rid of "Link Title" field altogether?

**Comment by wesruv** [comment]
That should do it!

Thanks!
