### ISSUE TITLE
Data Structure - Analyst

### ISSUE THREAD

**Issue by wesruv** [wesruv/jungcentralohio.org#34]
This content type is for organizing and listing Jungian Analysts

* Name
* Credentials
* Services Provided
* Diploma
* Phone # 
* E-mail Address
* Photo? (Ask Sydney if this is something they're interested in)

Related content from old site:
* https://github.com/wesruv/jungcentralohio.org/issues/18
* Maybe related? https://github.com/wesruv/jungcentralohio.org/issues/9 Might want to ask Sydney?

**Comment by wesruv** [comment]
@pascalmp any luck on this?

**Comment by pascalmp** [comment]
Hi Wes,
  

  
I'm working on it, will keep you posted when I get something to share!
    
  
  

  
  
   This (https://itunes.apple.com/app/apple-store/id922793622?pt=814382&mt=8&ct=how_i_email)  is how I Email now
  
  
  
  
  

  
  
>

**Comment by wesruv** [comment]
No problem, just wanted to see if you had any questions 😄

**Comment by pascalmp** [comment]
Hello, Wes,
I just had an unexpected last minute error.
i might have confused the dev environments,

I created a content type named Analysts (+Add Content Type)
Then I created as its fields:

Name
Credentials
Services Provided
Diploma
Phone #
E-mail Address
Photo

and saved.
but when I went on pantheon and cloned from Dev to pascalmp-1 , the link to pascalmpa-1 site returned an error page http://pascalmp-1-jaco.pantheonsite.io/

is there a way to reverse the cloning feature?

**Comment by pascalmp** [comment]
I created another MultiDev env called pascalmp-2, that's where i'm recreating the content type Analysts and its fields. I will not clone anything until the Scrum meeting. I realized when I first created the new content type it was on this link http://dev-jaco.pantheonsite.io/admin/structure/types/add , nothing was saved, now im in the right multidev env http://pascalmp-2-jaco.pantheonsite.io/admin/structure/types/manage/analysts/fields

**Comment by wesruv** [comment]
Hrmm it sounds like you cloned as the last step. I would clone as the first step, or not at all. Putting older configuration into a site with updates can definitely cause some issues.

**Comment by pascalmp** [comment]
haha, yeah, I thought so. The video tutorials i have been watching use an old UI (2013), the current UI look different and that confused me

**Comment by wesruv** [comment]
@pascalmp looking at your content type, one small piece of feedback:
We don't need an extra field for name, the "Title" field (currently called Analyst), can be called "Name", you can change that field's name in the "Configure" tab (not very intuitive).

**Comment by wesruv** [comment]
@pascalmp actually a few more more small things:
* We don't need "filtered text" on the credentials field, plain text is fine
* We should put "filtered text" on Services provided so that they can have bold, bulleted lists, etc.

**Comment by pascalmp** [comment]
oh ok, then how about the Body field and the Services Provided? are those the same?

**Comment by wesruv** [comment]
Let's keep those separate for now... this looks good to me.
