### ISSUE TITLE
Content Inventory - Gallery Section

### ISSUE THREAD

**Issue by wesruv** [wesruv/jungcentralohio.org#4]
Parent Issue: https://github.com/wesruv/jungcentralohio.org/issues/3

http://www.jungcentralohio.org/Gallery.html

Information we're trying to collect for the page above and it's sub-pages:
- [x] How the pages/section fit into the site-tree/navigation
- [x] Identify chunks of content that make up the page (e.g. the page is an 'event', but also has listings of upcoming events OR the page is the "about us page" but also has a listing of seminars, a summary of the lending library, and it lists the board members)
- [x] Identify any 'special' functionality or behaviors. This includes search, listings of content, animating/interactive elements, etc.
- [x] *Extra credit*, if you have any recommendations (e.g. this page might be better with a picture of X, or this piece of content could use a map, this page could be combined with another, etc)

**Comment by maryeb** [comment]
# **Jung Association Gallery**
 _Information on current and past visual art exhibits_

### Content areas include:
    Heading area with:
    - Page heading
    - Large logo image

    
     Section with:
    - Title “Current Exhibit”
    - Subtitle of specific exhibit
    - Large image of artist’s work
    - Title of image
    - Artist’s name
    - Date span of exhibit *
    - Short paragraph with date, time, description of artist visit and time exhibit opens with reception
    - Paragraph/ artist’s bio. Includes some repetition of info shared in the short paragraph noted above.
    - Subsection with address, phone number, gallery days/times
    (*I think it would be clearer if the date span for this exhibit was included with this information. Seems disjointed to me. Causing some potential confusion for user.)

**Comment by maryeb** [comment]
Section with:
  - Title “Past Exhibits”
  - Divs set up three columns across twenty-three rows down each div includes title of exhibit, artist’s name, date span
   - most divs include thumbnail image of artist’s work, clickable to view larger     

   Section with:
  - Title “Auctioned Items”
   One line describing beneficiary.
  - Two divs with thumbnail images of artwork, artist’s name, donor (where applicable)

**Comment by wesruv** [comment]
Looks great!
