### ISSUE TITLE
Content Inventory - Intro

### ISSUE THREAD

**Issue by wesruv** [wesruv/jungcentralohio.org#5]
Parent Issue: https://github.com/wesruv/jungcentralohio.org/issues/3

http://www.jungcentralohio.org/intro.html

Information we're trying to collect for the page above and it's sub-pages:
- [x] How the pages/section fit into the site-tree/navigation
- [x] Identify chunks of content that make up the page (e.g. the page is an 'event', but also has listings of upcoming events OR the page is the "about us page" but also has a listing of seminars, a summary of the lending library, and it lists the board members)
- [x] Identify any 'special' functionality or behaviors. This includes search, listings of content, animating/interactive elements, etc.
- [x] *Extra credit*, if you have any recommendations (e.g. this page might be better with a picture of X, or this piece of content could use a map, this page could be combined with another, etc)

**Comment by maryeb** [comment]
# Jung Association Intro
Overview of the organization

**Content areas include:** 

* Heading area with:
  * Title of organization, acronym, page heading 
    (Don't know that they need the organization title and acronym. Don't need acronym repeated twice)
* Section with:
   * Blocks of text describing purpose, location, membership, bookstore, and a list* arranged in two columns. No headings. (Need headings. Need space, better delineation between different content.) (The list* includes services and parking info. Needs a header. Parking info could be moved to content on location  )
* Section with:
   * Title “Bollinger Fund”Text description
* Section with:
   * Three lists 
      * Board of trustees
      * Board executive committee
      * JACO director
* Section with:
   * Statement of purpose
   * List of membership levels (title, description, cost)

**Comment by wesruv** [comment]
Great work!

The biggest problem with this page is it's a not so short description of content on the rest of the site, and is a little scattered. As @maryeb points out, it'd be great to put this content in the appropriate areas.
