### ISSUE TITLE
Content Inventory - Additional Resources

### ISSUE THREAD

**Issue by wesruv** [wesruv/jungcentralohio.org#6]
Parent Issue: https://github.com/wesruv/jungcentralohio.org/issues/3

http://www.jungcentralohio.org/resource_index.html

Information we're trying to collect for the page above and it's sub-pages:
- [x] How the pages/section fit into the site-tree/navigation
- [x] Identify chunks of content that make up the page (e.g. the page is an 'event', but also has listings of upcoming events OR the page is the "about us page" but also has a listing of seminars, a summary of the lending library, and it lists the board members)
- [x] Identify any 'special' functionality or behaviors. This includes search, listings of content, animating/interactive elements, etc.
- [x] *Extra credit*, if you have any recommendations (e.g. this page might be better with a picture of X, or this piece of content could use a map, this page could be combined with another, etc)

**Comment by maryeb** [comment]
# Other Jung Resources
Links to additional Jungian sites

**Content areas:**
Use Frameset with two windows

 * Navigation menu
 * Main area that can be replace by navigating in first.

(It looks like the frameset tag is not supported in HTML5. Forums suggest using jQuery, AJAX, iframe tag)

**Comment by wesruv** [comment]
@maryeb for the Content Inventory part of this we just want to focus on what content they've added here. Ignoring the frames.

For this one I'd say:
* Link (with link name and URL)
* Appears that these may be categorized somehow?

**Comment by maryeb** [comment]
@wesruv I made the changes.  Is this what you want? Anything else?

**Comment by wesruv** [comment]
That's very thorough, more than I expected, but that'll come in handy 😄
