### ISSUE TITLE
Content Inventory - Historic Building

### ISSUE THREAD

**Issue by wesruv** [wesruv/jungcentralohio.org#7]
Parent Issue: https://github.com/wesruv/jungcentralohio.org/issues/3

http://www.jungcentralohio.org/building.html

Information we're trying to collect for the page above and it's sub-pages:
- [x] How the pages/section fit into the site-tree/navigation
- [x] Identify chunks of content that make up the page (e.g. the page is an 'event', but also has listings of upcoming events OR the page is the "about us page" but also has a listing of seminars, a summary of the lending library, and it lists the board members)
- [x] Identify any 'special' functionality or behaviors. This includes search, listings of content, animating/interactive elements, etc.
- [x] *Extra credit*, if you have any recommendations (e.g. this page might be better with a picture of X, or this piece of content could use a map, this page could be combined with another, etc)

**Comment by maryeb** [comment]
# Jung Historic Building

Image of JACO building, "Jung House" with address

**Content includes:**
 * Header with title
 * Large image of building
 * address

Two ideas:
 1. Doesn’t need to be a separate page. If the content on the “Intro page is streamlined, a smaller version of this image could be added to the “Intro” page. “Into” page already contains information on address, location and hours of operation

 2. If they want to keep this page, remove the address, location, hours of operation content from the “Intro” page and just have the content on this page. If they have program participants that come from outside of Columbus, it would be nice to also add bit about the Short North/Victorian Village area where they are located, including information on restaurants and accommodations. )

**Comment by wesruv** [comment]
Great suggestions, looks good!
