### ISSUE TITLE
Content Inventory - OVAJA

### ISSUE THREAD

**Issue by wesruv** [wesruv/jungcentralohio.org#9]
Parent Issue: https://github.com/wesruv/jungcentralohio.org/issues/3

http://www.jungcentralohio.org/ovaja.html

Information we're trying to collect for the page above and it's sub-pages:
- [ ] How the pages/section fit into the site-tree/navigation
- [ ] Identify chunks of content that make up the page (e.g. the page is an 'event', but also has listings of upcoming events OR the page is the "about us page" but also has a listing of seminars, a summary of the lending library, and it lists the board members)
- [ ] Identify any 'special' functionality or behaviors. This includes search, listings of content, animating/interactive elements, etc.
- [ ] *Extra credit*, if you have any recommendations (e.g. this page might be better with a picture of X, or this piece of content could use a map, this page could be combined with another, etc)

**Comment by starbuck28** [comment]
# **OVAJA**

A page that will likely be linked to from a drop down menu on home page or from another major page

Content areas include:

**Main header** (text only)

**Intro**

- paragraph description of OVAJA

**Purpose**

- paragraph

 description

**Address and Officers**

- address of OVAJA
- contact person
- phone number
- email

**List of officers**

- Title and name of officer

**List of members**

- Name
- address
- phone number
- email
- website

**Comment by wesruv** [comment]
Perfect!
